package com.kapil.reddit.post.domain;

import com.kapil.reddit.community.domain.Community;
import com.kapil.reddit.user.domain.User;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.List;

@Entity
@Table(name = "posts")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Post {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "community_id")
    private Community community;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author_id")
    private User author;

    private String title;

    @Column(name = "original_text")
    private String originalText;

    @Column(name = "display_text")
    private String displayText;

    private Long upvotes;
    private Long downvotes;
    private Long score;
    private Long commentCount;
    private Long viewCount;

    private Double hotScore;

    private Boolean isModerated;
    private Boolean isDeleted;

    private Instant createdAt;
    private Instant updatedAt;

    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<PostMedia> media;

    /**
     * 384-dimensional text embedding generated by the ML service
     * (all-MiniLM-L6-v2 SentenceTransformer model).
     *
     * Stored as PostgreSQL vector(384) via the pgvector extension.
     * Hibernate maps it as a simple float array; pgvector handles
     * the binary wire format automatically via the custom type below.
     *
     * columnDefinition="vector(384)" prevents Hibernate from generating
     * incompatible DDL on schema validation.
     */
    @Column(name = "embedding", columnDefinition = "vector(384)")
    private float[] embedding;
}
